name: CI

on: push

jobs:
  change-check:
    runs-on: ubuntu-latest
    outputs:
      is-one-changed: ${{ steps.one-files.outputs.any_changed }}
      is-two-changed: ${{ steps.two-files.outputs.any_changed }}
      is-three-changed: ${{ steps.three-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check one diff
        uses: tj-actions/changed-files@v39
        id: one-files
        with:
          files: |
            one/**
            .github/workflows/ci.yml
            .github/workflows/test.yml
      - name: check two diff
        uses: tj-actions/changed-files@v39
        id: two-files
        with:
          files: |
            two/**
            .github/workflows/ci.yml
            .github/workflows/test.yml
      - name: check three diff
        uses: tj-actions/changed-files@v39
        id: three-files
        with:
          files: |
            three/**
            .github/workflows/ci.yml
            .github/workflows/test.yml

  one-ci:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      statuses: write
    needs: [change-check]
    if: needs.change-check.outputs.is-one-changed == 'true'
    uses: ./.github/workflows/test.yml
    with:
      working-directory: "./one"
      go-version: 1.21

  two-ci:
    permissions:
      contents: read
      pull-requests: write
    needs: [change-check]
    if: needs.change-check.outputs.is-two-changed == 'true'
    uses: ./.github/workflows/test.yml
    with:
      working-directory: "./two"
      go-version: 1.21

  three-ci:
    permissions:
      contents: read
      pull-requests: write
    needs: [change-check]
    if: needs.change-check.outputs.is-three-changed == 'true'
    uses: ./.github/workflows/test.yml
    with:
      working-directory: "./two"
      go-version: 1.21
